apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "torchserve-bert-v2"
spec:
  predictor:
    pytorch:
      protocolVersion: v2
      image: shrinathsuresh/torchserve-kfs:dev
      storageUri: s3://kubeflow-dataset/bert/kserve
